### ISSUE TITLE
Website accessories

### ISSUE THREAD

**Issue by bcjaeger** [MoTrPAC/MotrpacRatTraining6mo#24]
Some things we could add:

1. Badges
2. Hex sticker
3. Customized sections in the Reference page
4. A dedicated 'get started' tab in the navigation bar with a tutorial

I'm happy to take a stab at this and submit a pull request.

**Comment by nicolerg** [comment]
4 is resolved by #26

**Comment by nicolerg** [comment]
A "R-CMD-check" badge is added by #29

**Comment by nicolerg** [comment]
I think the only outstanding thing I want to address now is customized sections in the Reference page. @bcjaeger could you please provide some guidance or point me to an example in one of your packages?

**Comment by nicolerg** [comment]
Thanks, that was very helpful! Resolved by #31
