### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by bcjaeger** [MoTrPAC/MotrpacRatTraining6mo#25]
We can set up some nice automated checks to be run whenever we push updates to the repo:

1. code coverage computation
2. pkgdown deployment
3. R cmd check

I'm happy to help with this!

**Comment by nicolerg** [comment]
Thanks, Byron! Let's prioritize 2 when I get back, then get to the others ASAP.

**Comment by nicolerg** [comment]
2 and 3 addressed by #29. We will wait to add code coverage computational until more tests are added.
