### ISSUE TITLE
broken links to MotrpacRatTraining6moData objects

### ISSUE THREAD

**Issue by nicolerg** [MoTrPAC/MotrpacRatTraining6mo#27]
References to data objects in `MotrpacRatTraining6moData` within documentation for `MotrpacRatTraining6mo` are broken. 
 
For example, see links [here](https://motrpac.github.io/MotrpacRatTraining6mo/reference/combine_normalized_data.html).
 
Something that should be <https://motrpac.github.io/MotrpacRatTraining6moData/reference/TISSUE_ABBREV.html> is <https://rdrr.io/pkg/MotrpacRatTraining6moData/man/TISSUE_ABBREV.html> (broken)

**Comment by nicolerg** [comment]
@bcjaeger how did you get your documentation on rdrr.io? e.g. https://rdrr.io/github/bcjaeger/orsf2/man/aorsf-package.html

**Comment by bcjaeger** [comment]
Howdy! I'm not sure exactly how rdrr knows that `aorsf` is an R package but doesn't know `MotrpacRatTraining6moData` is one. It should incorporate all R packages on GitHub automatically.

I would try `usethis::use_package_doc()` to make a file for package-level documentation. This may be how rdrr identifies R packages on GitHub.

**Comment by nicolerg** [comment]
Thank you! I think I found the solution [here](https://pkgdown.r-lib.org/articles/linking.html#across-packages), i.e. add the GitHub pages URL to both `DESCRIPTION` and `_pkgdown.yml`. Working on it...

**Comment by nicolerg** [comment]
Unfortunately neither adding the pkgdown site URLs and rebuilding nor adding the file generated by `usethis::use_package_doc()` resolved this. I submitted https://github.com/r-lib/pkgdown/issues/2203 asking about cross-package linking and https://github.com/rdrr-io/rdrr-issues/issues/103 asking how/if these packages can be added to https://rdrr.io/.

**Comment by nicolerg** [comment]
Resolved! Possibly by updating `pkgdown` and `downlit`? But creating the `pkgdown` website with the GitHub Action resolved this.
